// Generated by CoffeeScript 1.3.3
(function() {
  var autoLink,
    __slice = [].slice;

  autoLink = function() {
    var callback, callbackOption, key, link_attributes, option, options, url_pattern, value;
    options = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    url_pattern = /(^|\s)(\b(https?):\/\/[\-A-Z0-9+&@#\/%?=~_|!:,.;]*[\-A-Z0-9+&@#\/%=~_|]\b)/ig;
    if (options.length > 0) {
      option = options[0];
      callbackOption = option.callback;
      if ((callbackOption != null) && typeof callbackOption === 'function') {
        callback = callbackOption;
        delete option.callback;
      }
      link_attributes = '';
      for (key in option) {
        value = option[key];
        link_attributes += " " + key + "='" + value + "'";
      }
      return this.replace(url_pattern, function(match, space, url) {
        var link, returnCallback;
        returnCallback = callback && callback(url);
        link = returnCallback || ("<a href='" + url + "'" + link_attributes + ">" + url + "</a>");
        return "" + space + link;
      });
    } else {
      return this.replace(url_pattern, "$1<a href='$2'>$2</a>");
    }
  };

  String.prototype['autoLink'] = autoLink;

}).call(this);
var p = document.getElementsByTagName('P');
for(var i = 0; i < p.length; i++) {
    p[i].innerHTML = p[i].innerHTML.autoLink();
}

if(typeof prettyPrint != 'undefined') {
    var c = document.getElementsByTagName('PRE');
    //var c = document.getElementsByTagName('CODE');
    for(var i = 0; i < c.length; i++) {
        c[i].className = 'prettyprint';
    }
    prettyPrint();
}

function mypipe(data) {
    var ul = document.getElementById('pipe');
    for(var i = 0; i < data.value.items.length; i++) {
        var item = data.value.items[i];
        var a = document.createElement('A');
        var li = document.createElement('LI');

        a.href = item.link;
        a.innerHTML = item.title;

        li.appendChild(a);
        ul.appendChild(li);
    }
}

if(document.getElementById('disqus_thread') && window.location.hostname != 'localhost') {
    var disqus_shortname = 'mbou';

    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
    dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
}

function toggleImgNoScale(e) {
    this.className = this.className == 'noscale' ? '' : 'noscale';
}
var imgs = document.getElementsByTagName('IMG');
for(var i = 0; i < imgs.length; i++) {
    imgs[i].onclick = toggleImgNoScale;
}
